version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
      - "8000:8000"

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

      NEXT_DISABLE_LIGHTNINGCSS: 1

    env_file:
      - ./.env

    restart: unless-stopped
